### ISSUE TITLE
修改当前进程的动态链接库行为

### ISSUE THREAD

**Issue by foreverhui** [esrrhs/hookso#1]
我需要hook 动态库中使用的pthread_create。然后hook函数定义在main函数中，请问我怎么使用您的代码，来修改当前进程的动态链接库行为？

**Comment by esrrhs** [comment]
这个hookso是个工具，改变其他进程的行为。你这种情况，是把调用pthread_create替换成pthread_create_new？这种参考下test就明白了

**Comment by foreverhui** [comment]
我的理解是在我自己main函数直接引入你的代码found函数和replace的实现，修改一下replace，直接替换动态库中函数的地址？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "esrrhs/hookso"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 晚上7:50
收件人:&nbsp;"esrrhs/hookso"<hookso@noreply.github.com&gt;;
抄送:&nbsp;"1084252004"<1084252004@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [esrrhs/hookso] 修改当前进程的动态链接库行为 (#1)





 
这个hookso是个工具，改变其他进程的行为。你这种情况，是把调用pthread_create替换成pthread_create_new？这种参考下test就明白了

**Comment by esrrhs** [comment]
同进程的话，没必要这么复杂了，直接&func取函数指针，写一个jmp完事

**Comment by foreverhui** [comment]
取我自己的函数指针我知道，jmp是怎么操作。我需要的修改的是通过dlopen加载的动态库，并且参数是RTLD_DEEPBIND，所以需要修改函数地址来进行hook。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "esrrhs/hookso"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 晚上9:30
收件人:&nbsp;"esrrhs/hookso"<hookso@noreply.github.com&gt;;
抄送:&nbsp;"1084252004"<1084252004@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [esrrhs/hookso] 修改当前进程的动态链接库行为 (#1)





 
同进程的话，没必要这么复杂了，直接&amp;func取函数指针，写一个jmp完事

**Comment by esrrhs** [comment]
参考这个：https://github.com/esrrhs/libmo/blob/master/src/mohook.h

**Comment by foreverhui** [comment]
十分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "esrrhs/hookso"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 晚上11:13
收件人:&nbsp;"esrrhs/hookso"<hookso@noreply.github.com&gt;;
抄送:&nbsp;"1084252004"<1084252004@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [esrrhs/hookso] 修改当前进程的动态链接库行为 (#1)





 
参考这个：https://github.com/esrrhs/libmo/blob/master/src/mohook.h

**Comment by foreverhui** [comment]
> 参考这个：https://github.com/esrrhs/libmo/blob/master/src/mohook.h

`auto handle = dlopen ("liba_new.so", RTLD_LAZY | RTLD_GLOBAL | RTLD_DEEPBIND); 
    //auto handle = dlopen ("liba_new.so", RTLD_LAZY | RTLD_GLOBAL); 
    fhook_func((uint8_t*)&pthread_create, (uint8_t*)pthread_create_new, old_pthread_create_hook_mem); `
尝试了一下，hook不能生效，
![image](https://user-images.githubusercontent.com/15011807/88871562-c7d10a80-d24a-11ea-941a-72d04517c16d.png)只对mian函数中的生效，不能对so库中的pthread_create产生hook.
![image](https://user-images.githubusercontent.com/15011807/88873300-f18c3080-d24e-11ea-9f8f-f98f6d667c1f.png)
上图是我的pthread_create_new，我用以下方式进行hook，so库中的函数，结果是hook到了，但是导致dlsym加载的pthread_create的也是我hook的，导致死循环，出现段错误。
`    pthread_create_fn f = (pthread_create_fn)dlsym(handle, "pthread_create");
    if ((error = dlerror()) != NULL)  {  
        fprintf (stderr, "%s ", error);  
        return 1;
    }  
    fhook_func((uint8_t*)f, (uint8_t*)pthread_create_new, old_so_pthread_create_hook_mem); 
`
运行截图如下：
![image](https://user-images.githubusercontent.com/15011807/88873412-31531800-d24f-11ea-8ac0-57dc7437b42d.png)
![image](https://user-images.githubusercontent.com/15011807/88873462-4334bb00-d24f-11ea-9298-681decd01a97.png)
上图是so中，使用pthread的代码。
请问您有什么好的解决方案吗？

**Comment by foreverhui** [comment]
我知道为啥死循环了，因为您的hook是修改机器码。然后相当于再调用一次newfunc，所以导致的嵌套调用。

**Comment by foreverhui** [comment]
```
before hook pthread_create, origin fn=0x400b70
my_pthread_create, origin fn=0x400d46
hook pthread_create, origin fn=0x7f924b2bc990
after hook pthread_create in main, origin fn=0x400b70
after hook pthread_create in so, origin fn=0x7f924b2bc990
```
我需要直接修改函数地址，才不会循环调用。

**Comment by esrrhs** [comment]
恩，上面那种修改机器码的hook，jmp出去，就不能再调回这个函数了

**Comment by foreverhui** [comment]
> 恩，上面那种修改机器码的hook，jmp出去，就不能再调回这个函数了

但是我不想重写一个pthread_create，我只是给线程传递一些上下文。

**Comment by foreverhui** [comment]
> 恩，上面那种修改机器码的hook，jmp出去，就不能再调回这个函数了

能加微信请教一下您吗？

**Comment by esrrhs** [comment]
> 
> 
> > 恩，上面那种修改机器码的hook，jmp出去，就不能再调回这个函数了
> 
> 但是我不想重写一个pthread_create，我只是给线程传递一些上下文。

那就找到plt的地址，改一下就好了，把hookso的部分代码拿过去

**Comment by foreverhui** [comment]
> > > 恩，上面那种修改机器码的hook，jmp出去，就不能再调回这个函数了
> > 
> > 
> > 但是我不想重写一个pthread_create，我只是给线程传递一些上下文。
> 
> 那就找到plt的地址，改一下就好了，把hookso的部分代码拿过去

我本来理解是直接把hookso部分代码拿过，newfunc地址就是直接pthread_create_new的地址，然后target_func地址就使用hookso的代码进行获取，但是看您的代码的时候发现目标函数在so里面的时候就看不懂了。
![image](https://user-images.githubusercontent.com/15011807/88902493-e05e1680-d284-11ea-974a-2eb0aa884bd7.png)
![image](https://user-images.githubusercontent.com/15011807/88902578-fcfa4e80-d284-11ea-8b7d-3f425d958294.png)
new的地址是0000000000400d46，这应该是在so里面的地址。您的replace逻辑，没看懂，
![image](https://user-images.githubusercontent.com/15011807/88902753-33d06480-d285-11ea-9d72-94a7d5f5ee1e.png)

**Comment by esrrhs** [comment]
pthread_create不会在你的so里面，这是属于系统的so，只需要把你old.so调用pthread_create的替换到new.so的pthread_create_new即可

**Comment by foreverhui** [comment]
> pthread_create不会在你的so里面，这是属于系统的so，只需要把你old.so调用pthread_create的替换到new.so的pthread_create_new即可

嗯，我尝试过把pthread_create_new写到一个new.so里面是可行的，但是pthread_create_new是实现在main函数里面不是so里面。

**Comment by foreverhui** [comment]
> pthread_create不会在你的so里面，这是属于系统的so，只需要把你old.so调用pthread_create的替换到new.so的pthread_create_new即可

谢谢改好了。到时候整理一下，请教您一下没看懂的原理。

**Comment by foreverhui** [comment]
find_so_func_addr_by_mem 和 find_so_func_addr_by_file，请问一下这两个函数的区别在哪里，我在使用的过程中发现某些so库使用find_so_func_addr_by_mem会出core。读取出来的setions信息和使用readelf读取的不对应。
```
Elf64_Shdr setions[targetso.e_shnum];
    try
    {
        ret = remote_process_read(pid, (void *) (sobeginvalue + targetso.e_shoff), &setions, sizeof(setions));
    }
```

**Comment by esrrhs** [comment]
> 
> 
> find_so_func_addr_by_mem 和 find_so_func_addr_by_file，请问一下这两个函数的区别在哪里，我在使用的过程中发现某些so库使用find_so_func_addr_by_mem会出core。读取出来的setions信息和使用readelf读取的不对应。
> 
> ```
> Elf64_Shdr setions[targetso.e_shnum];
>     try
>     {
>         ret = remote_process_read(pid, (void *) (sobeginvalue + targetso.e_shoff), &setions, sizeof(setions));
>     }
> ```

一些小的so被完全加载到内存了，可以用mem读。否则只能通过file读

**Comment by foreverhui** [comment]
谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "esrrhs/hookso"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:40
收件人:&nbsp;"esrrhs/hookso"<hookso@noreply.github.com&gt;;
抄送:&nbsp;"1084252004"<1084252004@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [esrrhs/hookso] 修改当前进程的动态链接库行为 (#1)





  
find_so_func_addr_by_mem 和 find_so_func_addr_by_file，请问一下这两个函数的区别在哪里，我在使用的过程中发现某些so库使用find_so_func_addr_by_mem会出core。读取出来的setions信息和使用readelf读取的不对应。
 Elf64_Shdr setions[targetso.e_shnum];     try     {         ret = remote_process_read(pid, (void *) (sobeginvalue + targetso.e_shoff), &amp;setions, sizeof(setions));     }   
一些小的so被完全加载到内存了，可以用mem读。否则只能通过file读

**Comment by yifannir** [comment]
请问一下关于“那就找到plt的地址，改一下就好了，把hookso的部分代码拿过去”怎么理解，我也遇到了这样的嵌套，进程A调用c.so，然后写的需要替换的b.so里面也依赖了c.so，这样使用b.so中的函数去替换进程A中的c.so也死循环了。
