### ISSUE TITLE
向Apache的子进程注入so失败

### ISSUE THREAD

**Issue by Wo0dsH0le** [esrrhs/hookso#13]
向Apache主进程注入so成功，但子进程会失败。
对比调试信息中仅一处不同，line:1683 显示子进程注入时，调用dlopen后返回的handle值为0。
添加dlerror()，但打印信息为空。

**Comment by esrrhs** [comment]
dlopen打开失败了吧，比如是不是缺了什么库导致

**Comment by Wo0dsH0le** [comment]
这是完整信息，但没看出问题，正阅读源码寻找中。
[root@localhost test]# ps -efH|grep httpd
root      22412   7242  0 22:29 pts/2    00:00:00           /usr/sbin/httpd -D NO_DETACH
apache    22413  22412  0 22:29 pts/2    00:00:00             /usr/sbin/httpd -D NO_DETACH
apache    22414  22412  0 22:29 pts/2    00:00:00             /usr/sbin/httpd -D NO_DETACH
apache    22415  22412  0 22:29 pts/2    00:00:00             /usr/sbin/httpd -D NO_DETACH
apache    22416  22412  0 22:29 pts/2    00:00:00             /usr/sbin/httpd -D NO_DETACH
apache    22417  22412  0 22:29 pts/2    00:00:00             /usr/sbin/httpd -D NO_DETACH
root      22497  22217  0 22:31 pts/1    00:00:00           grep --color=auto httpd

[root@localhost test]# ./hookso dlopen 22412 ./test.so 
[DEBUG][2024.11.26,22:32:16,698]main.cpp:2884,ini_hookso_env: start ini hookso env
[DEBUG][2024.11.26,22:32:16,702]main.cpp:2928,ini_hookso_env: ini hookso env glibcname=libc-2.17.so gpcalladdr=0x7f52f5516008 backupcode=216455366371460479 stack=0x7f52e7450000
[DEBUG][2024.11.26,22:32:16,702]main.cpp:1857,program_dlopen: pid=22412
[DEBUG][2024.11.26,22:32:16,702]main.cpp:1858,program_dlopen: target so=./test.so
[DEBUG][2024.11.26,22:32:16,702]main.cpp:1860,program_dlopen: start inject so file ./test.so
[DEBUG][2024.11.26,22:32:16,702]main.cpp:1651,inject_so: start inject so /home/pc/Desktop/test/test.so
[DEBUG][2024.11.26,22:32:16,706]main.cpp:371,find_so_func_addr_by_mem: find target so, begin with 0x7f52f5516000 139994279796736
[DEBUG][2024.11.26,22:32:16,706]main.cpp:387,find_so_func_addr_by_mem: read head ok 139994279796736
[DEBUG][2024.11.26,22:32:16,706]main.cpp:388,find_so_func_addr_by_mem: section offset 2151440
[DEBUG][2024.11.26,22:32:16,706]main.cpp:389,find_so_func_addr_by_mem: section num 75
[DEBUG][2024.11.26,22:32:16,706]main.cpp:390,find_so_func_addr_by_mem: section size 64
[DEBUG][2024.11.26,22:32:16,706]main.cpp:391,find_so_func_addr_by_mem: section header string table index 74
[DEBUG][2024.11.26,22:32:16,706]main.cpp:400,find_so_func_addr_by_mem: section header string table offset 2150168
[DEBUG][2024.11.26,22:32:16,706]main.cpp:401,find_so_func_addr_by_mem: section header string table size 1265
[DEBUG][2024.11.26,22:32:16,706]main.cpp:456,find_so_func_addr_by_mem: plt index 11
[DEBUG][2024.11.26,22:32:16,706]main.cpp:457,find_so_func_addr_by_mem: plt section offset 129296
[DEBUG][2024.11.26,22:32:16,706]main.cpp:458,find_so_func_addr_by_mem: plt section size 224
[DEBUG][2024.11.26,22:32:16,706]main.cpp:461,find_so_func_addr_by_mem: dynsym index 4
[DEBUG][2024.11.26,22:32:16,706]main.cpp:462,find_so_func_addr_by_mem: dynsym section offset 15752
[DEBUG][2024.11.26,22:32:16,706]main.cpp:463,find_so_func_addr_by_mem: dynsym section size 2243
[DEBUG][2024.11.26,22:32:16,706]main.cpp:472,find_so_func_addr_by_mem: dynstr index 5
[DEBUG][2024.11.26,22:32:16,706]main.cpp:473,find_so_func_addr_by_mem: dynstr section offset 69584
[DEBUG][2024.11.26,22:32:16,706]main.cpp:474,find_so_func_addr_by_mem: dynstr section size 23293
[DEBUG][2024.11.26,22:32:16,707]main.cpp:503,find_so_func_addr_by_mem: target text func addr 0x7f52f5653790
[DEBUG][2024.11.26,22:32:16,707]main.cpp:1660,inject_so: libc libc-2.17.so func __libc_dlopen_mode is 0x7f52f5653790
[DEBUG][2024.11.26,22:32:16,707]main.cpp:1540,alloc_so_string_mem: start syscall sys_mmap 29 4096
[DEBUG][2024.11.26,22:32:16,707]main.cpp:1561,alloc_so_string_mem: syscall sys_mmap ok 29 4096 0x7f52f7011000
[DEBUG][2024.11.26,22:32:16,708]main.cpp:1568,free_so_string_mem: start syscall sys_munmap 0x7f52f7011000 4096
[DEBUG][2024.11.26,22:32:16,708]main.cpp:1583,free_so_string_mem: syscall sys_munmap ok 0x7f52f7011000 4096
[DEBUG][2024.11.26,22:32:16,708]main.cpp:1683,inject_so: inject so /home/pc/Desktop/test/test.so ok handle=94800441114640
94800441114640
[DEBUG][2024.11.26,22:32:16,708]main.cpp:2945,fini_hookso_env: fini hookso env ok


[root@localhost test]# ./hookso dlopen 22413 ./test.so 
[DEBUG][2024.11.26,22:32:29,629]main.cpp:2884,ini_hookso_env: start ini hookso env
[DEBUG][2024.11.26,22:32:29,634]main.cpp:2928,ini_hookso_env: ini hookso env glibcname=libc-2.17.so gpcalladdr=0x7f52f5516008 backupcode=216455366371460479 stack=0x7f52e7247000
[DEBUG][2024.11.26,22:32:29,634]main.cpp:1857,program_dlopen: pid=22413
[DEBUG][2024.11.26,22:32:29,634]main.cpp:1858,program_dlopen: target so=./test.so
[DEBUG][2024.11.26,22:32:29,634]main.cpp:1860,program_dlopen: start inject so file ./test.so
[DEBUG][2024.11.26,22:32:29,634]main.cpp:1651,inject_so: start inject so /home/pc/Desktop/test/test.so
[DEBUG][2024.11.26,22:32:29,638]main.cpp:371,find_so_func_addr_by_mem: find target so, begin with 0x7f52f5516000 139994279796736
[DEBUG][2024.11.26,22:32:29,638]main.cpp:387,find_so_func_addr_by_mem: read head ok 139994279796736
[DEBUG][2024.11.26,22:32:29,638]main.cpp:388,find_so_func_addr_by_mem: section offset 2151440
[DEBUG][2024.11.26,22:32:29,638]main.cpp:389,find_so_func_addr_by_mem: section num 75
[DEBUG][2024.11.26,22:32:29,638]main.cpp:390,find_so_func_addr_by_mem: section size 64
[DEBUG][2024.11.26,22:32:29,638]main.cpp:391,find_so_func_addr_by_mem: section header string table index 74
[DEBUG][2024.11.26,22:32:29,638]main.cpp:400,find_so_func_addr_by_mem: section header string table offset 2150168
[DEBUG][2024.11.26,22:32:29,638]main.cpp:401,find_so_func_addr_by_mem: section header string table size 1265
[DEBUG][2024.11.26,22:32:29,638]main.cpp:456,find_so_func_addr_by_mem: plt index 11
[DEBUG][2024.11.26,22:32:29,638]main.cpp:457,find_so_func_addr_by_mem: plt section offset 129296
[DEBUG][2024.11.26,22:32:29,638]main.cpp:458,find_so_func_addr_by_mem: plt section size 224
[DEBUG][2024.11.26,22:32:29,638]main.cpp:461,find_so_func_addr_by_mem: dynsym index 4
[DEBUG][2024.11.26,22:32:29,638]main.cpp:462,find_so_func_addr_by_mem: dynsym section offset 15752
[DEBUG][2024.11.26,22:32:29,638]main.cpp:463,find_so_func_addr_by_mem: dynsym section size 2243
[DEBUG][2024.11.26,22:32:29,638]main.cpp:472,find_so_func_addr_by_mem: dynstr index 5
[DEBUG][2024.11.26,22:32:29,638]main.cpp:473,find_so_func_addr_by_mem: dynstr section offset 69584
[DEBUG][2024.11.26,22:32:29,638]main.cpp:474,find_so_func_addr_by_mem: dynstr section size 23293
[DEBUG][2024.11.26,22:32:29,639]main.cpp:503,find_so_func_addr_by_mem: target text func addr 0x7f52f5653790
[DEBUG][2024.11.26,22:32:29,639]main.cpp:1660,inject_so: libc libc-2.17.so func __libc_dlopen_mode is 0x7f52f5653790
[DEBUG][2024.11.26,22:32:29,639]main.cpp:1540,alloc_so_string_mem: start syscall sys_mmap 29 4096
[DEBUG][2024.11.26,22:32:29,639]main.cpp:1561,alloc_so_string_mem: syscall sys_mmap ok 29 4096 0x7f52f7011000
[DEBUG][2024.11.26,22:32:29,639]main.cpp:1568,free_so_string_mem: start syscall sys_munmap 0x7f52f7011000 4096
[DEBUG][2024.11.26,22:32:29,640]main.cpp:1583,free_so_string_mem: syscall sys_munmap ok 0x7f52f7011000 4096
[DEBUG][2024.11.26,22:32:29,640]main.cpp:1683,inject_so: inject so /home/pc/Desktop/test/test.so ok handle=0
[ERROR][2024.11.26,22:32:29,640]main.cpp:1687,inject_so: dlopen ./test.so fail
[DEBUG][2024.11.26,22:32:29,640]main.cpp:2945,fini_hookso_env: fini hookso env ok

**Comment by Wo0dsH0le** [comment]
> dlopen打开失败了吧，比如是不是缺了什么库导致

解决了，但原因不明，与之前遇到的一个问题相似——测试环境是centos7，之前编译时遇到过用-L指定动态库搜索路径后，不能生效，最终只能修改ld.so.conf添加so所在目录才解决。而现在这里的dlopen失败，也是so的路径问题，虽然so所在目录已在搜索路径中了，但只能将其放入/usr/lib64下才能成功。
