### ISSUE TITLE
.rela.dyn

### ISSUE THREAD

**Issue by foreverhui** [esrrhs/hookso#2]
如果动态库中函数在.rela.dyn表里面，有机会实现hook吗？我看相关资料都是修改rela.plt。

**Comment by esrrhs** [comment]
什么样的函数会在.rela.dyn里面

**Comment by foreverhui** [comment]
![image](https://user-images.githubusercontent.com/15011807/90730557-e5017200-e2fa-11ea-9582-6d91fe8e9950.png)
就是编译一个动态库，然后这个动态库引入了一个静态库。

**Comment by esrrhs** [comment]
你试试hookso能解决你的问题吗？我的理解你这种情况，也能hook，看看readme

**Comment by foreverhui** [comment]
> 你试试hookso能解决你的问题吗？我的理解你这种情况，也能hook，看看readme

不能解决，因为会找不到这个函数，
![image](https://user-images.githubusercontent.com/15011807/90731040-b0da8100-e2fb-11ea-963b-789d10dad805.png) hookso中只在rela.plt寻找函数地址。然后我尝试
![image](https://user-images.githubusercontent.com/15011807/90731079-c354ba80-e2fb-11ea-8aee-ba767affb411.png)
自己读取reladyn部分会出core。

**Comment by esrrhs** [comment]
你把代码或者二进制，打个包，我看看啥问题

**Comment by foreverhui** [comment]
发你邮箱了

**Comment by foreverhui** [comment]
其实我觉得应该也能修改rela.dyn表。不知道为啥读取不了。是因为没有加载到内存吗？



发自我的iPhone


------------------ Original ------------------

**Comment by foreverhui** [comment]
> 你把代码或者二进制，打个包，我看看啥问题

修改rela.dyn的实现了，但是好像有问题。
![image](https://user-images.githubusercontent.com/15011807/90850114-6c0a2500-e3a3-11ea-84d7-27f1b788f93a.png)
是因为重定位类型不是R_X86_64_JUMP_SLO而是R_X86_64_GLOB_DAT和R_X86_64_64？

**Comment by foreverhui** [comment]
因为我把栈写爆了，所以出core。修改rela.dyn本身没有问题

**Comment by esrrhs** [comment]
@foreverhui 下了你的程序了，你是想替换libLeafMediaProxy.so的free函数吗？

**Comment by foreverhui** [comment]
> @foreverhui 下了你的程序了，你是想替换libLeafMediaProxy.so的free函数吗？

是的，这个库里面free函数有两个地址，当时没注意到。

**Comment by esrrhs** [comment]
@foreverhui 那我的理解是hookso是能找到的libLeafMediaProxy.so的free函数的，在relaplt里
0000000000906790 <av_frame_free@plt>:
000000000093de90 <SSL_free@plt>:
000000000094f770 <av_free@plt>:
00000000009535a0 <RSA_free@plt>:
0000000000953ea0 <nx_json_free@plt>:

**Comment by esrrhs** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/15011807/90730557-e5017200-e2fa-11ea-9582-6d91fe8e9950.png)
> 就是编译一个动态库，然后这个动态库引入了一个静态库。

对于静态库的函数，其实已经在code section中了，hookso应该也能找到。而且你给的tcmalloc其实还是so的模式

**Comment by foreverhui** [comment]
> @foreverhui 那我的理解是hookso是能找到的libLeafMediaProxy.so的free函数的，在relaplt里
> 0000000000906790 [av_frame_free@plt](mailto:av_frame_free@plt):
> 000000000093de90 [SSL_free@plt](mailto:SSL_free@plt):
> 000000000094f770 [av_free@plt](mailto:av_free@plt):
> 00000000009535a0 [RSA_free@plt](mailto:RSA_free@plt):
> 0000000000953ea0 [nx_json_free@plt](mailto:nx_json_free@plt):

这几个free都不是我想hook的，想hook的在rela.dyn里面，就是原生的free。

**Comment by foreverhui** [comment]
> > ![image](https://user-images.githubusercontent.com/15011807/90730557-e5017200-e2fa-11ea-9582-6d91fe8e9950.png)
> > 就是编译一个动态库，然后这个动态库引入了一个静态库。
> 
> 对于静态库的函数，其实已经在code section中了，hookso应该也能找到。而且你给的tcmalloc其实还是so的模式

是的，是可以找到的。是因为free有两个地址，所以才出了问题。

**Comment by esrrhs** [comment]
> ela.dyn

其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到

**Comment by foreverhui** [comment]
> > ela.dyn
> 
> 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到

我看好像不在.text段里面。

**Comment by foreverhui** [comment]
> > ela.dyn
> 
> 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到

提个问题，为什么remote_process_write和remote_process_read需要分成那三种函数？

**Comment by esrrhs** [comment]
> 
> 
> > > ela.dyn
> > 
> > 
> > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> 
> 我看好像不在.text段里面。

free是在libc.so的

**Comment by esrrhs** [comment]
> 
> 
> > > ela.dyn
> > 
> > 
> > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> 
> 提个问题，为什么remote_process_write和remote_process_read需要分成那三种函数？

三种方式都可以吧，速度不同，哪种成功用哪种

**Comment by foreverhui** [comment]
第一种有时候会失败。第三种我没用过。



发自我的iPhone


------------------ Original ------------------

**Comment by foreverhui** [comment]
> > > > ela.dyn
> > > 
> > > 
> > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > 
> > 
> > 我看好像不在.text段里面。
> 
> free是在libc.so的

嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn

**Comment by esrrhs** [comment]
> 
> 
> > > > > ela.dyn
> > > > 
> > > > 
> > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > 
> > > 
> > > 我看好像不在.text段里面。
> > 
> > 
> > free是在libc.so的
> 
> 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn

libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面

**Comment by foreverhui** [comment]
> > > > > > ela.dyn
> > > > > 
> > > > > 
> > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > 
> > > > 
> > > > 我看好像不在.text段里面。
> > > 
> > > 
> > > free是在libc.so的
> > 
> > 
> > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> 
> libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面

你可以看下那个动态库，free在rela.dyn里面。

**Comment by esrrhs** [comment]
> 
> 
> > > > > > > ela.dyn
> > > > > > 
> > > > > > 
> > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > 
> > > > > 
> > > > > 我看好像不在.text段里面。
> > > > 
> > > > 
> > > > free是在libc.so的
> > > 
> > > 
> > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > 
> > 
> > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> 
> 你可以看下那个动态库，free在rela.dyn里面。

我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改

**Comment by foreverhui** [comment]
> > > > > > > > ela.dyn
> > > > > > > 
> > > > > > > 
> > > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > > 
> > > > > > 
> > > > > > 我看好像不在.text段里面。
> > > > > 
> > > > > 
> > > > > free是在libc.so的
> > > > 
> > > > 
> > > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > > 
> > > 
> > > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> > 
> > 
> > 你可以看下那个动态库，free在rela.dyn里面。
> 
> 我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改

我直接修改了rela.dyn里面的内容可以实现hook，直接替换r_offset地址的内容。

**Comment by foreverhui** [comment]
> > > > > > > > ela.dyn
> > > > > > > 
> > > > > > > 
> > > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > > 
> > > > > > 
> > > > > > 我看好像不在.text段里面。
> > > > > 
> > > > > 
> > > > > free是在libc.so的
> > > > 
> > > > 
> > > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > > 
> > > 
> > > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> > 
> > 
> > 你可以看下那个动态库，free在rela.dyn里面。
> 
> 我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改

R_X86_64_GLOB_DAT 0000000000000000 free@GLIBC_2.2.5 + 0 这个是刚刚您说的语句产生的，R_X86_64_64       0000000000000000 free@GLIBC_2.2.5 + 0 这个重定位类型的呢？

**Comment by esrrhs** [comment]
> 
> 
> > > > > > > > > ela.dyn
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > > > 
> > > > > > > 
> > > > > > > 我看好像不在.text段里面。
> > > > > > 
> > > > > > 
> > > > > > free是在libc.so的
> > > > > 
> > > > > 
> > > > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > > > 
> > > > 
> > > > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> > > 
> > > 
> > > 你可以看下那个动态库，free在rela.dyn里面。
> > 
> > 
> > 我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改
> 
> R_X86_64_GLOB_DAT 0000000000000000 free@GLIBC_2.2.5 + 0 这个是刚刚您说的语句产生的，R_X86_64_64 0000000000000000 free@GLIBC_2.2.5 + 0 这个重定位类型的呢？

![图片](https://user-images.githubusercontent.com/4083816/91020093-99b1d100-e624-11ea-85f2-64d6e00c21d4.png)
这个产生的是R_X86_64_GLOB_DAT 0000000000000000 free + 0

![图片](https://user-images.githubusercontent.com/4083816/91020166-b5b57280-e624-11ea-9170-c5d365586bcc.png)
这个产生的是R_X86_64_64       0000000000000000 free + 0

**Comment by foreverhui** [comment]
> > > > > > > > > > ela.dyn
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我看好像不在.text段里面。
> > > > > > > 
> > > > > > > 
> > > > > > > free是在libc.so的
> > > > > > 
> > > > > > 
> > > > > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > > > > 
> > > > > 
> > > > > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> > > > 
> > > > 
> > > > 你可以看下那个动态库，free在rela.dyn里面。
> > > 
> > > 
> > > 我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改
> > 
> > 
> > R_X86_64_GLOB_DAT 0000000000000000 free@GLIBC_2.2.5 + 0 这个是刚刚您说的语句产生的，R_X86_64_64 0000000000000000 free@GLIBC_2.2.5 + 0 这个重定位类型的呢？
> 
> ![图片](https://user-images.githubusercontent.com/4083816/91020093-99b1d100-e624-11ea-85f2-64d6e00c21d4.png)
> 这个产生的是R_X86_64_GLOB_DAT 0000000000000000 free + 0
> 
> ![图片](https://user-images.githubusercontent.com/4083816/91020166-b5b57280-e624-11ea-9170-c5d365586bcc.png)
> 这个产生的是R_X86_64_64 0000000000000000 free + 0

这个原理是因为其实调用的取值操作，所以重定位当做数据来处理？

**Comment by esrrhs** [comment]
> 
> 
> > > > > > > > > > > ela.dyn
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 其实不需要rela.dyn，要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我看好像不在.text段里面。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > free是在libc.so的
> > > > > > > 
> > > > > > > 
> > > > > > > 嗯，所以您“要么是code section，要么是rela.plt里，我刚才试了下，原生的free也能找到”这个意思是去直接修改libc.so?还是别的？我理解替换libLeafMediaProxy.so的free函数，只能修改libLeafMediaProxy的rela.dyn
> > > > > > 
> > > > > > 
> > > > > > libLeafMediaProxy的rela.plt里没有free吗？只要libLeafMediaProxy调用了free函数，就会存在rela.plt里面
> > > > > 
> > > > > 
> > > > > 你可以看下那个动态库，free在rela.dyn里面。
> > > > 
> > > > 
> > > > 我知道问题了，这个so是用了个func f = &free的语句，这种free就不在plt里面了。我看看怎么修改
> > > 
> > > 
> > > R_X86_64_GLOB_DAT 0000000000000000 free@GLIBC_2.2.5 + 0 这个是刚刚您说的语句产生的，R_X86_64_64 0000000000000000 free@GLIBC_2.2.5 + 0 这个重定位类型的呢？
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/4083816/91020093-99b1d100-e624-11ea-85f2-64d6e00c21d4.png)
> > 这个产生的是R_X86_64_GLOB_DAT 0000000000000000 free + 0
> > ![图片](https://user-images.githubusercontent.com/4083816/91020166-b5b57280-e624-11ea-9170-c5d365586bcc.png)
> > 这个产生的是R_X86_64_64 0000000000000000 free + 0
> 
> 这个原理是因为其实调用的取值操作，所以重定位当做数据来处理？

是的，所以在rela.dyn里面。这里面都是放变量的

**Comment by esrrhs** [comment]
@foreverhui 我更新了，针对这种函数地址存个变量的情况，也支持替换和查找

**Comment by foreverhui** [comment]
> @foreverhui 我更新了，针对这种函数地址存个变量的情况，也支持替换和查找

看到了，其实建议修改一下代码，把那些可能很大的局部变量改成使用堆内存，如果在线程里面调用hook加载很大的so会写爆栈。

**Comment by esrrhs** [comment]
> 
> 
> > @foreverhui 我更新了，针对这种函数地址存个变量的情况，也支持替换和查找
> 
> 看到了，其实建议修改一下代码，把那些可能很大的局部变量改成使用堆内存，如果在线程里面调用hook加载很大的so会写爆栈。

恩，确实是，你的这个so太大了，有这种问题。我看看怎么改

**Comment by foreverhui** [comment]
我改好了。直接使用的智能指针来hold住申请的内存。



发自我的iPhone


------------------ Original ------------------

**Comment by esrrhs** [comment]
> 
> 我改好了。直接使用的智能指针来hold住申请的内存。 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: zhao xin <notifications@github.com&gt; Date: Wed,Aug 26,2020 9:04 AM To: esrrhs/hookso <hookso@noreply.github.com&gt; Cc: learn-python-web <1084252004@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [esrrhs/hookso] .rela.dyn (#2) @foreverhui 我更新了，针对这种函数地址存个变量的情况，也支持替换和查找 看到了，其实建议修改一下代码，把那些可能很大的局部变量改成使用堆内存，如果在线程里面调用hook加载很大的so会写爆栈。 恩，确实是，你的这个so太大了，有这种问题。我看看怎么改 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我更新了下，针对这种大so，避免栈挂掉

**Comment by foreverhui** [comment]
@esrrhs 看到了。大佬效率太高了。
