### ISSUE TITLE
相对寻址函数hook

### ISSUE THREAD

**Issue by foreverhui** [esrrhs/hookso#3]
![image](https://user-images.githubusercontent.com/15011807/94414014-68da3400-01ae-11eb-85b2-79246ef9c8ee.png)
如上图，请问一下这种函数如何hook，他在相同的编译单元，不经过plt寻址。

**Comment by esrrhs** [comment]
没懂什么意思。换成一个hello world级别的代码说明一下看看？

**Comment by foreverhui** [comment]
```typedef struct link_map *(*dl_find_dso_for_object_t) (const ElfW(Addr) addr);
dl_find_dso_for_object_t dl_find_dso_for_object_f = (dl_find_dso_for_object_t)dlsym(RTLD_NEXT,"_dl_find_dso_for_object");
thread_local ElfW(Addr) caller_addr = 0; 

struct link_map *
dl_find_dso_for_object (const ElfW(Addr) addr)
{
    if(caller_addr != 0){
        LOG_ERROR << "use hook addr: " << addr << endl;
        return dl_find_dso_for_object_f(caller_addr);
    }
        
    return dl_find_dso_for_object_f(addr);
}
    hookFuncs["_dl_find_dso_for_object"] = (void *)&dl_find_dso_for_object;
    program_replace("/lib/x86_64-linux-gnu/libc-2.23.so", hookFuncs);
```
我通过这种方式准备hook libc种的`_dl_find_dso_for_object`函数，但是我发现不是所有调用`_dl_find_dso_for_object`的地方都是经过我hook的，然后用gdb单步调试发现`dl_open_worker`在调用`_dl_find_dso_for_object`的时候不会经过我的hook，因为这两个函数是在同一个编译单元。

**Comment by esrrhs** [comment]
没懂你的代码啥意思，表述也没明白。不过估计是因为你把函数指针写死在代码里，还是在栈上，所以编译器也直接写死了，这种情况你只能在函数头的地方加jump

**Comment by foreverhui** [comment]
> 没懂你的代码啥意思，表述也没明白。不过估计是因为你把函数指针写死在代码里，还是在栈上，所以编译器也直接写死了，这种情况你只能在函数头的地方加jump

我是要hook，libc动态库中的_dl_find_dso_for_object函数，然后第一张图是libc源码中使用这个函数的地方，我发现hook没有生效，然后我认为libc源码部分导致地址写死了，这种有什么好办法进行hook吗？我还是需要调用到原函数。因为我不能进行函数的实现。

**Comment by esrrhs** [comment]
你就改下test里的代码模拟下这种情况，应该是可以的。找不到_dl_find_dso_for_object应该是libc的原因，具体需要研究下了。建议你先把你看到的函数的写法，用test里的代码简单模拟一下，测试一下。我刚才试了下，libtest.so里两个函数内部调用是可以的

**Comment by foreverhui** [comment]
> 你就改下test里的代码模拟下这种情况，应该是可以的。找不到_dl_find_dso_for_object应该是libc的原因，具体需要研究下了。建议你先把你看到的函数的写法，用test里的代码简单模拟一下，测试一下。我刚才试了下，libtest.so里两个函数内部调用是可以的

![image](https://user-images.githubusercontent.com/15011807/94505993-f5ccce00-023e-11eb-9235-4eb64e383d8c.png)
![image](https://user-images.githubusercontent.com/15011807/94506002-f8c7be80-023e-11eb-9836-282767e1dd68.png)
应该是libc自己编译的问题了，不知道他怎么把地址写死的。

**Comment by esrrhs** [comment]
这个是正常的，同一个so的函数相互调用肯定是直接call的。关键是_dl_find_dso_for_object在so里没有看到函数定义。比如这样一个代码
```
static inline bool libtest2(int n) {
    char buff[128] = {0};
    snprintf(buff, sizeof(buff), "libtest %d", n);
    puts(buff);
    return false;
}

extern "C" bool libtest(int n) {
    return libtest2(n);
}

bool libtest3(int n) {
    return libtest(n);
}

static bool libtest4(int n) {
    return libtest2(n);
}
```
编译出来的，函数都能找到
```
objdump -d libtest.so|grep libtest
libtest.so：     文件格式 elf64-x86-64
0000000000000600 <libtest@plt>:
00000000000006f8 <_ZL8libtest2i>:
00000000000007c1 <libtest>:
 7d1:   e8 22 ff ff ff          callq  6f8 <_ZL8libtest2i>
00000000000007d8 <_Z8libtest3i>:
 7e8:   e8 13 fe ff ff          callq  600 <libtest@plt>
00000000000007ef <_ZL8libtest4i>:
 7ff:   e8 f4 fe ff ff          callq  6f8 <_ZL8libtest2i>
```
这种是没问题的，可以替换。

**Comment by esrrhs** [comment]
对于要hook没有导出的函数，可以把oldfunc函数所在代码段的内存复制出来，改成可执行的newfunc，再在oldfunc里做个跳转到newfunc

**Comment by foreverhui** [comment]
> 这个是正常的，同一个so的函数相互调用肯定是直接call的。关键是_dl_find_dso_for_object在so里没有看到函数定义。比如这样一个代码
> 
> ```
> static inline bool libtest2(int n) {
>     char buff[128] = {0};
>     snprintf(buff, sizeof(buff), "libtest %d", n);
>     puts(buff);
>     return false;
> }
> 
> extern "C" bool libtest(int n) {
>     return libtest2(n);
> }
> 
> bool libtest3(int n) {
>     return libtest(n);
> }
> 
> static bool libtest4(int n) {
>     return libtest2(n);
> }
> ```
> 
> 编译出来的，函数都能找到
> 
> ```
> objdump -d libtest.so|grep libtest
> libtest.so：     文件格式 elf64-x86-64
> 0000000000000600 <libtest@plt>:
> 00000000000006f8 <_ZL8libtest2i>:
> 00000000000007c1 <libtest>:
>  7d1:   e8 22 ff ff ff          callq  6f8 <_ZL8libtest2i>
> 00000000000007d8 <_Z8libtest3i>:
>  7e8:   e8 13 fe ff ff          callq  600 <libtest@plt>
> 00000000000007ef <_ZL8libtest4i>:
>  7ff:   e8 f4 fe ff ff          callq  6f8 <_ZL8libtest2i>
> ```
> 
> 这种是没问题的，可以替换。

![image](https://user-images.githubusercontent.com/15011807/94507133-a63bd180-0241-11eb-8937-593eef2fef45.png)
是有的，但是不是所有的函数都是plt
![image](https://user-images.githubusercontent.com/15011807/94507155-b2279380-0241-11eb-8573-7dea4123896e.png)

**Comment by esrrhs** [comment]
你这个截图里，写的就是_dl_find_dso_for_object@plt啊，应该没问题的，你直接找个进程用hookso试试

**Comment by foreverhui** [comment]
> 你这个截图里，写的就是_dl_find_dso_for_object@plt啊，应该没问题的，你直接找个进程用hookso试试

上面截图是_dl_addr函数调用_dl_find_dso_for_object，
![image](https://user-images.githubusercontent.com/15011807/94507897-53fbb000-0243-11eb-9679-3a99d2b4445c.png)
还有dl_open_worker调用_dl_find_dso_for_object，hook _dl_addr的调用没问题，但是worker的hook不到。

**Comment by esrrhs** [comment]
那就用我说的那种方法即可，对于要hook没有导出的函数，可以把oldfunc函数所在代码段的内存复制出来，改成可执行的newfunc，再在oldfunc里做个跳转到newfunc

**Comment by foreverhui** [comment]
> 那就用我说的那种方法即可，对于要hook没有导出的函数，可以把oldfunc函数所在代码段的内存复制出来，改成可执行的newfunc，再在oldfunc里做个跳转到newfunc

谢谢，请问有相关示例吗？

**Comment by esrrhs** [comment]
没有，应该简单吧，找到oldfunc函数地址，malloc一块内存，指针newfunc，memcpy(newfunc,oldfunc,1024*10)，再把newfunc设为可执行权限，后面就是jump了

**Comment by foreverhui** [comment]
> 没有，应该简单吧，找到oldfunc函数地址，malloc一块内存，指针newfunc，memcpy(newfunc,oldfunc,1024*10)，再把newfunc设为可执行权限，后面就是jump了

```    char *f = (char *)func;
	if (origFunc) {
		// find the return instruction retq: c3
		int index = 0;
		while (true) {
			if (static_cast<uint8_t>(f[index++]) == 0xc3 || index >= 1024) {
				break;
			}
		}

		void *old = malloc(index);
		if (old != nullptr) {
			memcpy(old, func, index);
			changeCodeAttrs(old, CODE_READ_ONLY);
			*origFunc = old;
		}
	}

    *(uint16_t *)&f[0] = 0x25ff;
    *(int *)&f[2] = 0x00000000;
    *(long *)&f[6] = (long)newAddr;
```
您看下，我这样hook有啥问题吗？

**Comment by esrrhs** [comment]
不懂，你可以参考这里 https://github.com/esrrhs/libmo/blob/master/src/mohook.h
