### ISSUE TITLE
我按照你的方法操作，hookso报错了

### ISSUE THREAD

**Issue by lmclmc** [esrrhs/hookso#6]
hookso 报了这个错误 [ERROR][2021.10.2,19:11:8,905]main.cpp:1271,syscall_so: the target process unexpectedly stopped by signal 11

**Comment by esrrhs** [comment]
> 
> 
> hookso 报了这个错误 [ERROR][2021.10.2,19:11:8,905]main.cpp:1271,syscall_so: the target process unexpectedly stopped by signal 11

哪个系统哪个平台呢？

**Comment by lmclmc** [comment]
ubuntu系统 X86平台

**Comment by esrrhs** [comment]
目前是只适用于x64平台，x86需要你修改下代码才行，包括函数调用方式、指针大小等等细节

**Comment by lmclmc** [comment]
好的，谢谢，那么请问有没有关于hook相关的学习资料和书籍呢？

**Comment by esrrhs** [comment]
> 
> 
> 好的，谢谢，那么请问有没有关于hook相关的学习资料和书籍呢？
没有吧
