### ISSUE TITLE
利用绝对地址跳转简化逻辑分支

### ISSUE THREAD

**Issue by xfyzfish** [esrrhs/hookso#7]
对于非got调用方式，将如下指令写入old_func_addr内存中，可直接跳转到new_func_addr，以此简化offset大小判断的分支代码
    char code[14] = {0};
    code[0] = 0xff;
    code[1] = 0x25;
    code[2] = 0x00;
    code[3] = 0x00;
    code[4] = 0x00;
    code[5] = 0x00;
    memcpy(&code[6], &new_func_addr, sizeof(new_func_addr));

gcc -O2参数默认对函数进行16字节对齐，不用担心code指令会写到其他函数空间
非-O2编译时，可以加上-falign-functions=16参数指定对函数进行16字节对齐

**Comment by esrrhs** [comment]
挺好的方法，不过限定了必须16字节对齐，就先不改了

**Comment by javapracticer** [comment]
你好，想请教一下，最近参照此项目自己也写了一个injec程序，在实验时候发现，某些程序调用其dlopen后读取其寄存器，rax返回值是0，一直排查到原因，想请大佬们指教下

**Comment by esrrhs** [comment]
> 

预期是什么呢
