### ISSUE TITLE
关于find地址

### ISSUE THREAD

**Issue by Littlerock-man** [esrrhs/hookso#9]
请问这里不能find = mapping[0].second么？测试直接使用没啥问题！
![image](https://user-images.githubusercontent.com/38898618/164582589-d20ae68b-9dcd-4dda-b69f-c726966448ec.png)

**Comment by esrrhs** [comment]
7f6efe36f000-7f6f00744000 ---p 00000000 00:00 0 
7f6f00744000-7f6f00745000 rw-p 00000000 00:00 0 
7f6f00745000-7f6f00bbe000 ---p 00000000 00:00 0 
7f6f00bbe000-7f6f00bbf000 rw-p 00000000 00:00 0 
7f6f00bbf000-7f6f00c3e000 ---p 00000000 00:00 0 
7f6f00c3e000-7f6f00c9e000 rw-p 00000000 00:00 0 

类似于这样，我理解是前闭后开的区间

**Comment by Littlerock-man** [comment]
但是实际计算下来find就是=mapping[0].second

**Comment by Littlerock-man** [comment]
还是有可能有其它情况？

**Comment by esrrhs** [comment]
实际上改成 find <= mapping[i].second 也没有差别，这段代码目的是找一块没有被占用的内存区间，然后下面申请新的。
